### ISSUE TITLE
first_server : Contenth-Length

### ISSUE THREAD

**Issue by funderburkjim** [marcwan/NodeLiveLessons#3]
I'm watching your NodeLiveLessons via safari online.
In Lesson 1.4, I noticed that in line 7 of first_server.js,  there is a spelling error:
`Contenth-Length` should be `Content-Length`.

Yet, this causes no problem when you run the code -- curl doesn't seem to care either.

I just wondered why this spelling error seems to have no effect?

**Comment by marcwan** [comment]
I suspect that most browsers / servers are smart enough to figure it out on their own. 

Thanks for spotting this !!!
